/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('stats').del();
    await knex('stats').insert([
        {
            character_id: 1,
            strength: 40,
            dexterity: 50,
            constitution: 50,
            size: 60,
            appearance: 60,
            intelligence: 70,
            education: 70,
            power: 80,
            build: 0,
            health: 11,
            movement: 8,
            sanity: 80,
            magic_points: 16,
            luck: 50
        },
        {
            character_id: 2,
            strength: 60,
            dexterity: 80,
            constitution: 50,
            size: 70,
            appearance: 70,
            intelligence: 60,
            education: 40,
            power: 50,
            build: 0,
            health: 12,
            movement: 8,
            sanity: 50,
            magic_points: 10,
            luck: 50
        },
        {
            character_id: 3,
            strength: 40,
            dexterity: 60,
            constitution: 70,
            size: 50,
            appearance: 80,
            intelligence: 50,
            education: 70,
            power: 60,
            build: 0,
            health: 12,
            movement: 8,
            sanity: 60,
            magic_points: 12,
            luck: 50
        },
        {
            character_id: 4,
            strength: 60,
            dexterity: 70,
            constitution: 60,
            size: 40,
            appearance: 50,
            intelligence: 70,
            education: 80,
            power: 50,
            build: 0,
            health: 10,
            movement: 8,
            sanity: 50,
            magic_points: 10,
            luck: 50
        },
        {
            character_id: 5,
            strength: 40,
            dexterity: 70,
            constitution: 50,
            size: 50,
            appearance: 60,
            intelligence: 80,
            education: 70,
            power: 60,
            build: 0,
            health: 10,
            movement: 8,
            sanity: 60,
            magic_points: 12,
            luck: 50
        },
        {
            character_id: 6,
            strength: 80,
            dexterity: 60,
            constitution: 70,
            size: 70,
            appearance: 40,
            intelligence: 60,
            education: 50,
            power: 50,
            build: 0,
            health: 14,
            movement: 8,
            sanity: 50,
            magic_points: 10,
            luck: 50
        },
        {
            character_id: 7,
            strength: 60,
            dexterity: 80,
            constitution: 60,
            size: 50,
            appearance: 70,
            intelligence: 70,
            education: 50,
            power: 40,
            build: 0,
            health: 11,
            movement: 8,
            sanity: 40,
            magic_points: 8,
            luck: 50
        },
        {
            character_id: 8,
            strength: 40,
            dexterity: 50,
            constitution: 70,
            size: 50,
            appearance: 60,
            intelligence: 60,
            education: 80,
            power: 70,
            build: 0,
            health: 12,
            movement: 8,
            sanity: 70,
            magic_points: 14,
            luck: 50
        },
    ]);
};